### ISSUE TITLE
[Good news] PyTomoATT now can be installed via conda directly

### ISSUE THREAD

**Issue by xumi1993** [TomoATT/PyTomoATT#25]
@mnagaso @JingChen-Thu 
@TomoATT/ntu-users @TomoATT/community-users 
I have uploaded PyTomoATT to [conda-forge](https://anaconda.org/conda-forge/pytomoatt). Now we can install it via

```
conda install pytomoatt -c conda-forge
```

**Comment by mnagaso** [comment]
Thank you very much!
